### ISSUE TITLE
Update names of data structures

### ISSUE THREAD

**Issue by dbyr** [dbyr/rb_tree#11]
Clippy doesn't like that my types are named `RB` instead of `Rb`. I don't really want to rename them, but if there's no way to stop clippy complaining I might have to

**Comment by eadf** [comment]
Just activate #![allow(non_camel_case_types)] globally or use one #[allow(non_camel_case_types)] per offending declaration.

Personally I have no problems with the name RB_* , it is an abbreviation after all.

**Comment by dbyr** [comment]
That doesn't seem to work unfortunately... Clippy still complains about it (see the run [here](https://github.com/dbyr/rb_tree/runs/2385852524)).

**Comment by dbyr** [comment]
Got it

**Comment by eadf** [comment]
Hm, I think `#[allow(clippy::style)]` disables all of clippy style guides for that block, if you replace that line with just 
`#[allow(non_camel_case_types)]` only the camel case test is ignored.

**Comment by dbyr** [comment]
Yeah, you're right. I thought I had tried a similar approach before but it didn't work. Well, it worked this time lol. Because it's clippy specific it seems `#[allow(clippy::upper_case_acronyms)]` was the way to go.
