### ISSUE TITLE
[Question] add benchmark tools?

### ISSUE THREAD

**Issue by eadf** [dbyr/rb_tree#13]
How would you feel about adding benchmark tests?
I've been using criterion and I think it works great. You can easily see if modifications improve the performance or not.
But it would require one more [dev-dependencies]

I could copy&paste from the examples I've been using into a simple PR for rb_tree if you like

**Comment by dbyr** [comment]
Sure that might be useful. I've been thinking about updating the inner workings of the library for a while now anyway, so that might be useful for making sure I've actually improved it and not made it worse lol
