### ISSUE TITLE
This project is lacking a license file in the root folder

### ISSUE THREAD

**Issue by fmease** [dbyr/rb_tree#8]
I don't think that the line `license = "MIT OR Apache-2.0"` in the `Cargo.toml` is enough.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

https://choosealicense.com/no-permission/

**Comment by dbyr** [comment]
Thanks for the advice! I have added it in fd92e5c005283aedeb0cc21dccf2ad2c302e1307
